#!/usr/bin/env python2

def sourc(env_name):
    import logging
    try:
        import imp
        imp.load_source('activate_this', env_name + '/bin/activate_this.py')
    except IOError:
        logging.warn('could not source virtualenv ' + env_name)


def run_debug():
    from website import app
    from os import environ
    app.secret_key = environ.get('SECRET_KEY', 'very secure')
    app.debug = True
    app.run(port=49155)


if __name__ == '__main__':
    import sys
    if (sys.argv) == 1:
        source(sys.argv[1])
    run_debug()
