"""empty message

Revision ID: 124310097c9
Revises: 3012ff7fab91
Create Date: 2014-03-11 14:55:41.537704

"""

# revision identifiers, used by Alembic.
revision = '124310097c9'
down_revision = '3012ff7fab91'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=220), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('added', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('authors', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('safe', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('safe')
    )
    op.create_table('document_categories',
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], )
    )
    op.drop_table('doc_category')
    op.drop_table('document')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('file', sa.VARCHAR(length=220), nullable=True),
    sa.Column('title', sa.VARCHAR(length=128), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('added', sa.DATETIME(), nullable=True),
    sa.Column('type', sa.VARCHAR(length=64), nullable=True),
    sa.Column('authors', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doc_category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('safe', sa.VARCHAR(length=128), nullable=True),
    sa.Column('document_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], [u'document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('document_categories')
    op.drop_table('categories')
    op.drop_table('documents')
    ### end Alembic commands ###
