"""empty message

Revision ID: 2816f280e9cf
Revises: 3e32d656c88d
Create Date: 2014-02-20 09:24:39.299164

"""

# revision identifiers, used by Alembic.
revision = '2816f280e9cf'
down_revision = '3e32d656c88d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doc_category', sa.Column('safe', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doc_category', 'safe')
    ### end Alembic commands ###
