"""empty message

Revision ID: 3012ff7fab91
Revises: 6d40d5a5d7f
Create Date: 2014-03-07 16:37:16.085587

"""

# revision identifiers, used by Alembic.
revision = '3012ff7fab91'
down_revision = '6d40d5a5d7f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('receives_messages', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'receives_messages')
    ### end Alembic commands ###
