"""empty message

Revision ID: 38a370264f47
Revises: 59009ef40e71
Create Date: 2014-02-20 02:37:24.179625

"""

# revision identifiers, used by Alembic.
revision = '38a370264f47'
down_revision = '59009ef40e71'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doc_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'document', sa.Column('added', sa.DateTime(), nullable=True))
    op.add_column(u'document', sa.Column('description', sa.Text(), nullable=True))
    op.add_column(u'document', sa.Column('title', sa.String(length=128), nullable=True))
    op.add_column(u'document', sa.Column('type', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'document', 'type')
    op.drop_column(u'document', 'title')
    op.drop_column(u'document', 'description')
    op.drop_column(u'document', 'added')
    op.drop_table('doc_category')
    ### end Alembic commands ###
