"""empty message

Revision ID: 3c08be371a6d
Revises: defa9db9471
Create Date: 2014-03-30 14:21:28.590631

"""

# revision identifiers, used by Alembic.
revision = '3c08be371a6d'
down_revision = 'defa9db9471'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('featured', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'featured')
    ### end Alembic commands ###
