"""empty message

Revision ID: 3d33dcde8c36
Revises: None
Create Date: 2014-02-20 13:35:31.238639

"""

# revision identifiers, used by Alembic.
revision = '3d33dcde8c36'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('photo', sa.String(length=220), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('href', sa.String(length=120), nullable=True),
    sa.Column('contact', sa.Text(), nullable=True),
    sa.Column('current', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenic_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(length=220), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('added', sa.DateTime(), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=220), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('added', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=24), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.Column('last_keychange', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('name')
    )
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password_hash', sa.String(length=87), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('username')
    )
    op.create_table('doc_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('safe', sa.String(length=128), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doc_category')
    op.drop_table('admin')
    op.drop_table('partner')
    op.drop_table('document')
    op.drop_table('photo')
    op.drop_table('scenic_photo')
    op.drop_table('person')
    ### end Alembic commands ###
