"""empty message

Revision ID: 3e32d656c88d
Revises: 38a370264f47
Create Date: 2014-02-20 02:42:35.873048

"""

# revision identifiers, used by Alembic.
revision = '3e32d656c88d'
down_revision = '38a370264f47'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
