"""empty message

Revision ID: 6d40d5a5d7f
Revises: 3d33dcde8c36
Create Date: 2014-02-27 12:48:52.412679

"""

# revision identifiers, used by Alembic.
revision = '6d40d5a5d7f'
down_revision = '3d33dcde8c36'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('authors', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'authors')
    ### end Alembic commands ###
